export const HELP_TEXT = [
  'HELP',
  'SIGNUP <email> <password> <display_name> [role]',
  'LOGIN <email> <password>',
  'LOGOUT',
  'WORLD        (list worlds)',
  'PORTAL <#>   (switch world)',
  'MAP          (list places)',
  'ENTER <#>    (enter place)',
  'LEAVE',
  'LOOK         (details for current place)',
  'JOBS         (jobs in current place)',
  'WHO          (list nearby users)',
  'SAY <msg>',
  'WAVE',
  'TAK <who#>   (tak tak a nearby user)',
  'DROP         (drop resume at current place)',
  'UNLOCK <job#>',
  'PROFILE'
];
