ALTER TABLE businesses ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

ALTER TABLE users ADD COLUMN IF NOT EXISTS home_world_id UUID REFERENCES worlds(id) ON DELETE SET NULL;
